
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 7;
  public static final int LBRACKET = 45;
  public static final int POWER = 28;
  public static final int MULT = 26;
  public static final int CHAR = 5;
  public static final int CONCAT = 42;
  public static final int POOL = 12;
  public static final int SEC = 10;
  public static final int LPAREN = 43;
  public static final int GREATER = 31;
  public static final int INT = 2;
  public static final int LESS = 32;
  public static final int MINUS = 25;
  public static final int RPAREN = 44;
  public static final int SEMICOLON = 49;
  public static final int AND = 39;
  public static final int NOT = 38;
  public static final int IN = 41;
  public static final int OR = 40;
  public static final int TDEF = 19;
  public static final int COMMA = 50;
  public static final int BOOL = 9;
  public static final int FI = 17;
  public static final int DIV = 27;
  public static final int RAT = 4;
  public static final int LOOP = 11;
  public static final int PLUS = 24;
  public static final int ASSIGN = 36;
  public static final int LESSEQ = 33;
  public static final int MAIN = 23;
  public static final int IF = 13;
  public static final int ID = 52;
  public static final int DOT = 30;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int RBRACKET = 46;
  public static final int EQUAL = 35;
  public static final int error = 1;
  public static final int NULL = 51;
  public static final int BREAK = 16;
  public static final int FDEF = 20;
  public static final int TOP = 8;
  public static final int COLON = 29;
  public static final int LBRACE = 47;
  public static final int ELSE = 15;
  public static final int READ = 18;
  public static final int FLOAT = 3;
  public static final int RBRACE = 48;
  public static final int THEN = 14;
  public static final int GREATEREQ = 34;
  public static final int STRING = 6;
  public static final int PRINT = 21;
  public static final int NOTEQ = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "RAT",
  "CHAR",
  "STRING",
  "SEQ",
  "TOP",
  "BOOL",
  "SEC",
  "LOOP",
  "POOL",
  "IF",
  "THEN",
  "ELSE",
  "BREAK",
  "FI",
  "READ",
  "TDEF",
  "FDEF",
  "PRINT",
  "RETURN",
  "MAIN",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "POWER",
  "COLON",
  "DOT",
  "GREATER",
  "LESS",
  "LESSEQ",
  "GREATEREQ",
  "EQUAL",
  "ASSIGN",
  "NOTEQ",
  "NOT",
  "AND",
  "OR",
  "IN",
  "CONCAT",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "COMMA",
  "NULL",
  "ID"
  };
}

